poormans_uptime_checker.pmuc.*:
  type: config_entity
  label: 'Poor Mans Uptime Checker Host Configuration Entity'
  mapping:
    id:
      type: string
      label: 'ID'
    hostname:
      type: string
      label: 'Hostname'
    last_message:
      type: string
      label: 'Last Error'
    status:
      type: string
      label: 'Last Known Status'
